services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "weather_stream:1:1"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  data-producer:
    build: ./kafka-producer
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./kafka-producer:/app
    working_dir: /app

  data-consumer:
    build:
      context: ./kafka-consumer
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./kafka-consumer:/app
    working_dir: /app



volumes:
  grafana-storage: {}

